### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by ribsousa** [MatissJanis/oc-testimonials#1]
**October version 184**
plugin shows the message successfully installed, but does not appear in the menu bar and the list of installed plugins

**Comment by MatissJanis** [comment]
Oh, that's an old version. Would You mind updating and trying to install this plugin again?

**Comment by ribsousa** [comment]
I installed the current version

**Comment by MatissJanis** [comment]
Currently the latest one we have is [build 229](https://github.com/octobercms/october/commit/ff5f17d6a36cf9025129f970e9cb0d72ec078f10)

**Comment by ribsousa** [comment]
ERROR
We're sorry, but an unhandled error occurred. Please see the details below.

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'iepmdf.mja_testimonials_testimonials' doesn't exist (SQL: select count(*) as aggregate from `mja_testimonials_testimonials`)
/home/storage/d/69/ea/iepmdf/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php line 625
TYPE

Undefined

EXCEPTION

Illuminate\Database\QueryException

619
620
621
622
623
624
625
626
627
628
629
630
631

```
    // If an exception occurs when attempting to run a query, we'll format the error
    // message to include the bindings with SQL, which will make this exception a
    // lot more helpful to the developer instead of just the database's errors.
    catch (\Exception $e)
    {
        throw new QueryException(
            $query, $this->prepareBindings($bindings), $e
        );
    }

    return $result;
}
```

 STACK TRACE

# CALLED CODE DOCUMENT    LINE

41  Illuminate\Database\Connection->runQueryCallback(…)   http://iepmdf.com.br/vendor/laravel/framework/src/Illuminate/Database/Connection.php    581
40  Illuminate\Database\Connection->run(…)    http://iepmdf.com.br/vendor/laravel/framework/src/Illuminate/Database/Connection.php    304
39  Illuminate\Database\Connection->select(…) http://iepmdf.com.br/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php 1398
38  Illuminate\Database\Query\Builder->runSelect()  http://iepmdf.com.br/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php 1383
37  Illuminate\Database\Query\Builder->getFresh(…)    http://iepmdf.com.br/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php 1370
36  Illuminate\Database\Query\Builder->get(…) http://iepmdf.com.br/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php 1816
35  Illuminate\Database\Query\Builder->aggregate(…)   http://iepmdf.com.br/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php 1754
34  Illuminate\Database\Query\Builder->count()  http://iepmdf.com.br/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php 1665
33  Illuminate\Database\Query\Builder->getPaginationCount() http://iepmdf.com.br/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php  274
32  Illuminate\Database\Eloquent\Builder->ungroupedPaginate(…)    http://iepmdf.com.br/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php  246
31  Illuminate\Database\Eloquent\Builder->paginate(…) http://iepmdf.com.br/modules/backend/widgets/Lists.php  459
30  Backend\Widgets\Lists->getRecords() http://iepmdf.com.br/modules/backend/widgets/Lists.php  195
29  Backend\Widgets\Lists->prepareVars()    http://iepmdf.com.br/modules/backend/widgets/Lists.php  183
28  Backend\Widgets\Lists->render() http://iepmdf.com.br/modules/backend/behaviors/ListController.php   285
27  Backend\Behaviors\ListController->listRender()  
26  call_user_func_array(…)   http://iepmdf.com.br/vendor/october/rain/src/Extension/ExtendableTrait.php  284
25  October\Rain\Extension\Extendable->extendableCall(…)  http://iepmdf.com.br/vendor/october/rain/src/Extension/Extendable.php   44
24  October\Rain\Extension\Extendable->__call(…)  http://iepmdf.com.br/plugins/mja/testimonials/controllers/testimonials/index.htm    2
23  Mja\Testimonials\Controllers\Testimonials->listRender() http://iepmdf.com.br/plugins/mja/testimonials/controllers/testimonials/index.htm    2
22  include(…)    http://iepmdf.com.br/modules/system/traits/ViewMaker.php    204
21  Backend\Classes\Controller->makeFileContents(…)   http://iepmdf.com.br/modules/system/traits/ViewMaker.php    78
20  Backend\Classes\Controller->makeView(…)   http://iepmdf.com.br/modules/backend/classes/Controller.php 329
19  Backend\Classes\Controller->execPageAction(…) http://iepmdf.com.br/modules/backend/classes/Controller.php 233
18  Backend\Classes\Controller->run(…)    http://iepmdf.com.br/modules/backend/classes/BackendController.php  67
17  Backend\Classes\BackendController->run(…)  
16  call_user_func_array(…)   http://iepmdf.com.br/vendor/laravel/framework/src/Illuminate/Routing/Controller.php 231
15  Illuminate\Routing\Controller->callAction(…)  http://iepmdf.com.br/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php   93
14  Illuminate\Routing\ControllerDispatcher->call(…)  http://iepmdf.com.br/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php   62
13  Illuminate\Routing\ControllerDispatcher->dispatch(…)  http://iepmdf.com.br/vendor/laravel/framework/src/Illuminate/Routing/Router.php 962
12  Illuminate\Routing\Router->Illuminate\Routing{closure}(…)  
11  call_user_func_array(…)   http://iepmdf.com.br/vendor/laravel/framework/src/Illuminate/Routing/Route.php  109
10  Illuminate\Routing\Route->run(…)  http://iepmdf.com.br/vendor/laravel/framework/src/Illuminate/Routing/Router.php 1028
9   Illuminate\Routing\Router->dispatchToRoute(…) http://iepmdf.com.br/vendor/laravel/framework/src/Illuminate/Routing/Router.php 996
8   Illuminate\Routing\Router->dispatch(…)    http://iepmdf.com.br/vendor/laravel/framework/src/Illuminate/Foundation/Application.php 775
7   Illuminate\Foundation\Application->dispatch(…)    http://iepmdf.com.br/vendor/laravel/framework/src/Illuminate/Foundation/Application.php 745
6   Illuminate\Foundation\Application->handle(…)  http://iepmdf.com.br/vendor/laravel/framework/src/Illuminate/Session/Middleware.php 72
5   Illuminate\Session\Middleware->handle(…)  http://iepmdf.com.br/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php   47
4   Illuminate\Cookie\Queue->handle(…)    http://iepmdf.com.br/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php   51
3   Illuminate\Cookie\Guard->handle(…)    http://iepmdf.com.br/vendor/stack/builder/src/Stack/StackedHttpKernel.php   23
2   Stack\StackedHttpKernel->handle(…)    http://iepmdf.com.br/vendor/laravel/framework/src/Illuminate/Foundation/Application.php 641
1   Illuminate\Foundation\Application->run()    http://iepmdf.com.br/index.php  40

**Comment by MatissJanis** [comment]
Looks like You downloaded it, but it did not install successfuly. Try running `php artisan plugin:refresh Mja.Testimonials`.

**Comment by ribsousa** [comment]
How to remove it manually?

**Comment by MatissJanis** [comment]
You can remove it manually by deleting it via the OctoberCMS Backend panel, or you can run `php artisan plugin:remote Mja.Testimonials`.

**Comment by ribsousa** [comment]
Checked in the database it is not in there, the plugins tables

**system_plugin_history
system_plugin_versions**

**Comment by MatissJanis** [comment]
Try running `php artisan plugin:refresh Mja.Testimonials`.

**Comment by ribsousa** [comment]
My projetc is published online have no way to run the command

**Comment by MatissJanis** [comment]
Then You have to create [this](https://github.com/MatissJA/oc-testimonials/blob/master/updates/create_testimonial_table.php) table manually.

**Comment by ribsousa** [comment]
I manually deleted the folder mja server since it did not create the table in the database and will not appear on the menu bar

**Comment by abass** [comment]
I just tried installing this plugin aswell, fresh install, and it's not showing up on the menu or within the plugins section. It has installed the proper plugins folder, it is just not showing up in the project at all.

**Comment by MatissJanis** [comment]
It may just be that you are missing the `Rainlab.Translate` plugin.

**Comment by abass** [comment]
That fixes it, though it seems like a very odd and unnecessary dependency? What is it being used for exactly?

Thanks!

**Comment by MatissJanis** [comment]
For creating the testimonials in multiple languages. Localization.

**Comment by abass** [comment]
I understand what the translate plugin does, I am just trying to understand why it is a dependency for your plugin is what I mean. It seems strange to me that another plugin is a dependency even if it is never actually used.

I see you require it [here](https://github.com/MatissJanis/oc-testimonials/blob/7a6e310ec37dbdf8fca7c02dc4d3640ae10f8b6d/Plugin.php#L12) and check if it's installed [here](https://github.com/MatissJanis/oc-testimonials/blob/8552ac9dbda1d3ee1f8b06010a22c1bfc7b2d564/models/Testimonial.php#L66), just trying to understand why you made it a necessity even if the user never creates testimonials in multiple languages is all I'm trying to understand.

**Comment by MatissJanis** [comment]
To be honest - I don't remember why I made it required. Thanks for noticing this! You are welcome to submit a PR with a fix :+1:

**Comment by abass** [comment]
@MatissJanis unfortunately, I am more of a front-end developer. I am not too familiar with how you would go about keeping the translate/localization option still available while just removing the translate plugin as a dependency. I'm assuming it would just be by removing the `public $require = ['RainLab.Translate'];` in the plugin.php while still keeping the [check for translate plugin](https://github.com/MatissJanis/oc-testimonials/blob/8552ac9dbda1d3ee1f8b06010a22c1bfc7b2d564/models/Testimonial.php#L66) in the testimonial.php, though I am not completely sure.

I appreciate the plugin nonetheless, thanks!

**Comment by MatissJanis** [comment]
Thanks! Fixed it :+1:
