### ISSUE TITLE
Title is Awkward & Overflows Containers

### ISSUE THREAD

**Issue by abass** [MatissJanis/oc-testimonials#2]
The plugin title is not implemented properly so it gives it a really awkward name and overflows all containers:

![](http://cl.ly/image/1e0q1d2u0Y0V/Image%202015-04-22%20at%2012.58.03%20AM.png)

And the same title in the sidebar (included other plugins to show how the titles look in other plugins)

![](http://cl.ly/image/3y330P2M313Q/Image%202015-04-22%20at%201.29.39%20AM.png)

**Comment by MatissJanis** [comment]
Thanks! :+1:

**Comment by abass** [comment]
You got it! Appreciate the quick fix :clap:
