### ISSUE TITLE
Custom markup not displaying any testimonials

### ISSUE THREAD

**Issue by matthewerskine** [MatissJanis/oc-testimonials#3]
Hi, thanks for your plugin! I am trying to write custom markup for this plugin so that I can present testimonials in a different way than in the default, however, the 'testimonials' variable becomes empty when custom markup is spawned by pressing the fork icon within the october editor. It will only display testimonials if the default markup is used.

Works:

<img width="346" alt="screen shot 2015-10-27 at 02 55 43" src="https://cloud.githubusercontent.com/assets/7579504/10748257/46a79180-7c56-11e5-9ddc-8c45b9aec18b.png">

Doesn't work:

<img width="491" alt="screen shot 2015-10-27 at 02 55 59" src="https://cloud.githubusercontent.com/assets/7579504/10748267/4f988362-7c56-11e5-969b-41a2601c48b9.png">

Any help appreciated!

**Comment by MatissJanis** [comment]
Overwrite the default partial (create a new file at `themes/active/partials/testimonials/default.htm`). [More information](http://octobercms.com/docs/cms/components#moving-default-markup).

**Comment by matthewerskine** [comment]
Thanks man
